# Generated by Django 6.0.5 on 2026-05-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark Mode'), ('light', 'Light Mode')], default='dark', max_length=10),
        ),
    ]
