# Generated by Django 6.0.5 on 2026-06-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('sunset-saffron', 'Sunset Saffron (Tricolor)'), ('royal-ashoka', 'Royal Ashoka Blue'), ('lotus-pink', 'Lotus Pink / Rose'), ('vibrant-emerald', 'Vibrant Emerald'), ('cyber-tricolor', 'Cyber Neon'), ('classic-light', 'Classic Light Mode')], default='sunset-saffron', max_length=30),
        ),
    ]
