# Generated by Django 6.0.5 on 2026-06-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('sunset-saffron', 'Sunset Saffron (Tricolor)'), ('royal-ashoka', 'Royal Ashoka Blue'), ('lotus-pink', 'Lotus Pink / Rose'), ('vibrant-emerald', 'Vibrant Emerald'), ('cyber-tricolor', 'Cyber Neon'), ('classic-light', 'Classic Light Mode'), ('holi-festival', 'Holi Festival (Colorful)'), ('midnight-slate', 'Midnight Slate'), ('sunset-magenta', 'Sunset Magenta'), ('ocean-turquoise', 'Ocean Turquoise'), ('sakura-blossom', 'Sakura Blossom (Pink & Plum)'), ('cosmic-lavender', 'Cosmic Lavender (Violet Neon)'), ('nordic-aurora', 'Nordic Aurora (Arctic Mint)'), ('desert-amber', 'Desert Amber (Oasis Gold)')], default='sunset-saffron', max_length=30),
        ),
    ]
