# Generated by Django 6.0.5 on 2026-06-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('classic-light', 'Classic Light'), ('sunset-saffron', 'Sunset Saffron (Charcoal & Amber)'), ('royal-ashoka', 'Royal Ashoka Blue (Dark Deep Blue)'), ('vibrant-emerald', 'Nordic Sage (Dark Sage Green)'), ('cosmic-lavender', 'Cosmic Lavender (Dark Indigo-Violet)')], default='sunset-saffron', max_length=30),
        ),
    ]
