# Generated by Django 6.0.5 on 2026-05-30 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Positive = requester pays extra. Negative = requester receives extra.', max_digits=10)),
                ('message', models.TextField(blank=True, help_text='Message to the other party')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('offered_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_offers', to='shop.product')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('target_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_targets', to='shop.product')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exchange Request',
                'verbose_name_plural': 'Exchange Requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExchangeTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('request_sent', 'Exchange Request Sent'), ('request_viewed', 'Request Viewed'), ('counter_offer', 'Counter Offer Made'), ('accepted', 'Exchange Accepted'), ('meetup_arranged', 'Meetup Arranged'), ('item_handed_over', 'Items Handed Over'), ('completed', 'Exchange Completed'), ('rejected', 'Exchange Rejected'), ('cancelled', 'Exchange Cancelled')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='swap.exchangerequest')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
